### ISSUE TITLE
Invalid zip

### ISSUE THREAD

**Issue by videopix** [boblemaire/asyncHTTPrequest#16]
Hi there,
I could not use the zip file downloaded here in the Arduino IDE. Ist complaining About an invalid library Format. Could you please have a look?
Thanks!

**Comment by boblemaire** [comment]
Sorry, I don't use the Arduino IDE, I use platform IO.  I don't remember how that works in Arduino IDE, but the relevant files are in the directory src.  You will also need to add ESPAsyncTCP to your libraries.

**Comment by bertmelis** [comment]
I suppose you're welcome to create a PR.
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification
