### ISSUE TITLE
Missing library.properties

### ISSUE THREAD

**Issue by devops-provectusalgae** [boblemaire/asyncHTTPrequest#18]
The repository is missing the library.properties file to be able to use this library with Arduino IDE.

Suggested content:
```
name=asyncHTTPrequest
version=1.2.1
author=Bob Lemaire
maintainer=Bob Lemaire
sentence=Simple async HTTP to sit on ESPAsyncTCP.
paragraph=Simple async HTTP to sit on ESPAsyncTCP.
category=Communication
url=https://github.com/boblemaire/asyncHTTPrequest.git
architectures=*
```

**Comment by boblemaire** [comment]
Don't use Arduino IDE, but looks good, how about a PR?

**Comment by andreas-provectusalgae** [comment]
I've created the pull request.
We're planning to move to PlatformIO, but support for Arduino IDE can't hurt ;)

**Comment by boblemaire** [comment]
PR was merged
