### ISSUE TITLE
Can't make secure HTTP (HTTPS) request

### ISSUE THREAD

**Issue by autosoft-co** [boblemaire/asyncHTTPrequest#22]
Hi everyone,

I'm unable to perform requests to HTTPS Endpoints. the requests are failing with exception.

Let me know if you guys need the logs.

Thank you.

**Comment by boblemaire** [comment]
Sorry, the library only supports HTTP requests.  HTTPS is not possible on the ESP8266 due to heap issues.  On the ESP32, the underlying asyncTCP does not have support for HTTPS.
