### ISSUE TITLE
URL without trailing '/' after address causes crash on ESP32

### ISSUE THREAD

**Issue by thorlancaster** [boblemaire/asyncHTTPrequest#30]
When attempting to connect to a HTTP server, I found that URLs where the address portion was not ended with a '/' character caused a crash.

URLs that cause crash: http://172.105.151.207, http://172.105.151.207:1230, http://172.105.151.207:1230?foo=bar
URLs that don't cause crash: http://172.105.151.207/, http://172.105.151.207:1230/, http://172.105.151.207:1230/?foo=bar.

(Note: The IP address, especially port 1230, will likely change in the future,  but I hope you see the pattern).

It's easy enough to fix on my end by adding a '/' to the URL between the address and the arguments, but this shouldn't be happening.

**Comment by boblemaire** [comment]
Resolved in rewrite of parseURL PR#32
