### ISSUE TITLE
Following redirects?

### ISSUE THREAD

**Issue by Nightsd01** [boblemaire/asyncHTTPrequest#34]
I am a bit of a n00b when it comes to the fundamental principles of how the HTTP protocol works in depth. 

When I receive a 301 redirect response, how should I handle this? Should I close the existing request and allocate a new request using the new location URL? Or is there an easier/better way to do it?

I am thinking about making a PR to add an option for automatically following redirects but I am not sure of the best approach

**Comment by boblemaire** [comment]
I'd recommend you pursue the redirect URL at your level rather than blindly follow the instruction in asyncHTTPrequest.  A common redirect is to require HTTPS in response to a HTTP request.  asyncHTTPrequest cannot do that.  I hope that helps, I'm going to close this.
