### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by blazeyzem** [boblemaire/asyncHTTPrequest#35]
Hello.

Does it support https?

**Comment by boblemaire** [comment]
No, it doesn't, but I have just thrown a follow-on class into my repo called esp32HTTPrequest that does.  I have been using this for a few weeks and it is working for my needs, but no extensive testing has been done.  I made some quick notes in the readme to explain the present state.  If you use it, please report any issues, or better yet fix them and send a PR.
