### ISSUE TITLE
a complete working example

### ISSUE THREAD

**Issue by ramarro123** [boblemaire/asyncHTTPrequest#4]
hi, any change to have a complete and working and compiling example with post, get and everything it's expected, to have a preview of the lib?

**Comment by boblemaire** [comment]
It's used in my iotawatt project, specifically in Emonservice.cpp and influx.cpp, and also to do a short query then download a large binary file in updater.cpp.
If I get some free time, I'll try to put together a simple GET and/or POST, but there are so many variations on how this can be used that it would require a dozen or more to explore the capabilities.
