### ISSUE TITLE
Crash after second request to not accessible target

### ISSUE THREAD

**Issue by andrewk123** [boblemaire/asyncHTTPrequest#41]
I have an ESP8266 IOT sending "push messages" to a NodeJS server.  All works fine as long as the server is available and responds to the requests.

If however the server is not available then I get the following behavior.

- IOT sends first request after initialization : http.readyState() before sending is 0.  A callback with a response code of -4 is generated after approx. 30 secs.  Setting http.setTimeout to a large (60) or small (1) value has no impact on this timeout.
- If you wait until the first request "times out" before the IOT sends its second request then you get a http.readyState() before sending of 4 and when the second packet times out with a response code of -4 all is good
- If you wait until the second request "times out" before the IOT sends its third request then you get a http.readyState() before sending of 4 and when the third request times out with a response code of -4 all is good
- If however the IOT sends its third request **before** receiving the -4 response code (associated with the second request) the http.readyState() before sending is 0. When the second request times out with a response code of -4 all is good.  However when the third request times out the ESP restarts immediately.

If I modify my code to only send on a http.readyState() of 4 after the first request is sent (after initialization the http.readyState() is always 0) then the crashes are avoided.

Questions:  

1.  Is it possible to decrease the "-4" timeout when the remote device is not available. 
2. Is there any way to avoid the crash other than by only sending requests (after the initial one) when the http.readyState()  is 4?

Thanks for your help with this one.

**Comment by boblemaire** [comment]
Can you set debug true and run that sequence to the crash, then post the complete debug output?

**Comment by andrewk123** [comment]
I had a quick look at this.  The restart appears to be caused by (in my example above) the second connection attempt de-allocating _client when the onDisconnect handler fires while the the third connection attempt is still active.  The third attempt then tries to re-use the already deallocated _client causing the restart.  As I said, I can work around this by looking for the http.readyState() to be 4 (not 0) (after the first connect attempt) and queuing/retrying subsequent messages until the previous attempt has timed out.  This stops the resets.

However, we still have the issue that there is a  (+/-) 30 sec timeout before the onDisconnect  event turns up even though the application "knows" it "*can't send" after less than 20 ms.  Any thoughts on how to abort the connection and/or fire the onDisconnect event?  I've tried using the abort() command after a timeout however that has no effect.  Any thoughts appreciated.

**Comment by miwied** [comment]
Hello, I have the excact same problems.

Here is my [example code](https://gist.github.com/miwied/4fea68dc27db63d038cefd8c0a753a1a) and here is [the reboot msg](https://gist.github.com/miwied/1e2bd80b97792a4ce437be2b53bbe04a).

**Comment by miwied** [comment]
@andrewk123 did you solve the timout problem?

**Comment by andrewk123** [comment]
I tried AsyncHTTPRequest_Generic and found the same issue, however Khoi was able to resolve it so I use that version now.  It's functionally identical to asyncHTTPrequest. There were some small changes to integrate it but nothing that took more than a few minutes.  The fix was in 1.4.0.

https://github.com/khoih-prog/AsyncHTTPRequest_Generic

**Comment by miwied** [comment]
@andrewk123 Hi first of all thanks for your answer!

Thats actually pretty funny because I struggeled for weeks to get either boblemaire's or khoih-progs library to work properly.
After days of no success I created a issue which let khoih to make a new version with a fix. [Here is his answer to my issue.](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/38#issuecomment-1232453703)

 Unfortunately till today I didn't get a working version.. 
 After the "fix" it still takes always 18 seconds to get a bad connection response. You can see my demo-code + debug output [here](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/38#issuecomment-1232593675).

Which microcontroller do you use?

**Comment by boblemaire** [comment]
Looks like a solution was found in another's fork.

**Comment by miwied** [comment]
@boblemaire Wich one?
