### ISSUE TITLE
HTTP:// in URL is case sensitive, won't accept http://

### ISSUE THREAD

**Issue by ramarro123** [boblemaire/asyncHTTPrequest#5]
i am not 100% it's intended but, without documentation it's hard so i dig a bit on code and found

>     _URL->scheme = new char[8];
>     strcpy(_URL->scheme, "HTTP://");
>     if(url.startsWith("HTTP://")) {
>        hostBeg += 7; 
>     }
> 

my url was http:// and it doesn't work... converting it with uppercase make it work apparently.
doing a touppercase doesn't seems a good idea, cos parameters get uppercase as well.

**Comment by boblemaire** [comment]
That's something that's easily done without converting the whole String to uppercase:

`if(url.substring(0,7).equalsIgnoreCase("HTTP://")){`

Can you send a PR?

**Comment by ramarro123** [comment]
probably done :) first PR so not sure if i did it correctly
